### ISSUE TITLE
./main.go:62:3: undefined: discordSession

### ISSUE THREAD

**Issue by r1axodn** [clinet/discordgo-embed#3]
import (
	"flag"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"github.com/Clinet/discordgo-embed"
	"github.com/bwmarrin/discordgo"
)
//...

func messageCreate(s *discordgo.Session, msg *discordgo.MessageCreate) {
	if msg.Author.ID == s.State.User.ID { // 만약에 해당 메세지를 보낸 사람의 ID가 봇 ID가 같을시 리턴
		return
	}

	if msg.Content == "gopher test" { 
		s.ChannelMessageSend(msg.ChannelID, "test")
	}

	if msg.Content == "gopher kaizer" {
		s.ChannelMessageSend(msg.ChannelID, "babo")
	}
	
	if msg.Content == "gopher embed" {
		discordSession.ChannelSendEmbed(msg.ChannelID, embed.NewGenericEmbed("Test", "못참치"))
	}

}

**Comment by normal8781** [comment]
(한국어로 답해드립니다)

1. messageCreate의 매개변수를 `s *discordgo.Session, msg *discordgo.MessageCreate)` 로 선언 하셨기 때문에 `discordSession` 이 아닌 `s` 를 사용해야 합니다. 

2. 이건 예외인데, 임베드를 보내려면 `s.ChannelMessageSendEmbed()` 를 사용해야 합니다. 

`ChannelSendEmbed`를 쓰라고 한건 이쪽에서 잘못 작성했거나, 버전이 다른거 같네요. 
¯\_(ツ)_/¯


```go
if msg.Content == "gopher embed" {
	s.ChannelMessageSendEmbed(msg.ChannelID, embed.NewGenericEmbed("Test", "못참치"))
}
```

**Comment by r1axodn** [comment]
#
